general:
  work_dir: "/fast/users/altwassr_c/scratch/P1104/preprocessing"
  region_file: "/fast/users/altwassr_c/work/umi-data-processing/umi-preprocessing/merged_probe_Charite_AG_DKMS_Panel_V5p1_TE-92294000_hg38.bed"
  barcode_file: "/fast/users/altwassr_c/scratch/data/P1104/P1104_barcode_file2.csv"
  library_file: "/fast/users/altwassr_c/scratch/data/P1104/P1104_library_file2.csv"
  demux: TRUE

reference:  
  genome: "/fast/users/altwassr_c/work/refs/GRCh38.u2af1_fix.v1.2020_04_01.fa"
  known_indels: "/fast/users/altwassr_c/work/umi-data-processing/umi-preprocessing/refs/dbsnp.vcf.gz"

illumina:
  basecall_dir: "/fast/users/altwassr_c/work/data/210827_A00643_0304_AHFFLNDRXY/Data/Intensities/BaseCalls/"
  readstructure: "147T8B10M8B147T"
  runbarcode: "2020"
  lane: "2"

picard:
  memoryusage: "-Xmx64g -Xms64g"

fgbio:
  groupreads: "-s adjacency"
  callconsensus: "-M 3"
  fextra: ""
  fminq: 5
