inputdir: /fast/work/users/hablesrr_c/20210216_Savvina/umi-variantcalling/dedup # source of raw sequencing run data
workdir: /fast/work/users/hablesrr_c/20210216_Savvina/umi-variantcalling/output_test # here your results are created
snakedir: /fast/work/users/hablesrr_c/20210216_Savvina/umi-variantcalling
bedfile: /fast/users/hablesrr_c/work/20210216_Savvina/umi-variantcalling/DKMS_v5_CHIPpanel_hg38.bed
refgenome: /fast/work/users/hablesrr_c/20210216_Savvina/umi-preprocessing/refs/genome.fasta

#### ABSOLUTE PATHS ############
paths:
  mystatic: /fast/groups/ag_damm/work/ref/
  bihstatic: /fast/projects/cubit/current/static_data
  scripts: scripts/ # folder relative to snakedir

#### TOOLS SECTION ##############
tools:
  annovar: perl /fast/users/hablesrr_c/work/Tools/annovar
mpileup:
  Q: 20   # base quality
  MAPQ: 10 # -q in pileup
annovar:
  build: hg38
  path_to_humandb: /fast/users/hablesrr_c/work/annovar/humandb
  annofiles:
    - refGene
    - cytoBand
    - clinvar_20200316
    - dbnsfp35c
    - gnomad30_genome
    - avsnp150
    - cosmic92_coding
    - cosmic92_noncoding
    - revel
    - nci60
edit:
  extended_output: False
  candidate_list: /fast/users/hablesrr_c/work/20210216_Savvina/umi-variantcalling/backup/info/AML_candidates.txt
  driver_list: /fast/users/hablesrr_c/work/20210216_Savvina/umi-variantcalling/backup/info/AML_drivers.txt
  CHIP_list: /fast/users/hablesrr_c/work/20210216_Savvina/umi-variantcalling/backup/info/CHIP_mut.txt
  normals: /fast/users/hablesrr_c/work/20210216_Savvina/umi-variantcalling/backup/configs/PON_UMI.txt
filter_bam:
    threads: 4
    stringency_for_IGVnav: moderate
    padding: 200
    folder: filterbam
primer3:  # is applied after filter step 1
  threads: 10
  min_size: 120
  max_size: 220
  center_offSet: 5 # how much offSet primer pairs can
  use_primer_list: ''
HDR:
  threads: 2
  min_HDR_count: 1 # minimum lanes around mutation to make it a putative HDR
  min_similarity: .85 # which similarities to consider as HDR
  padding: 150  # range around mutation to be scanned
  min_q: 20 # minimum base quality to be used for HDR-calculation
