general:
  work_dir: "/data/gpfs-1/users/altwassr_c/scratch/P1081/demux"
  region_file: "/fast/users/altwassr_c/work/refs/merged_probe_file_combined_Charite_AG_DKMS_Panel_V5p1update_TE-93192476_hg38.bed"
  barcode_file_prefix: "/data/gpfs-1/users/altwassr_c/scratch/data/P1081/P1081_barcode"
  library_file_prefix: "/data/gpfs-1/users/altwassr_c/scratch/data/P1081/P1081_library_params"
  demux: TRUE

reference:  
  genome: "/fast/users/altwassr_c/work/refs/GRCh38.u2af1_fix.v1.2020_04_01.fa"
  known_indels: "/fast/users/altwassr_c/work/umi-data-processing/umi-preprocessing/refs/dbsnp.vcf.gz"

illumina:
  basecall_dir: "/data/gpfs-1/users/altwassr_c/scratch/data/P1081/210709_A00643_0275_AHGCH3DRXY/Data/Intensities/BaseCalls/"
  readstructure: "148T8B9M8B148T"
  runbarcode: "2020"
  lane: ["1","2"]

picard:
  memoryusage: "-Xmx64g -Xms64g"

fgbio:
  groupreads: "-s adjacency"
  callconsensus: "-M 3"
  fextra: ""
  fminq: 5
