general:
  work_dir: "/fast/users/altwassr_c/scratch/P1162/demux"
  region_file: "/fast/users/altwassr_c/work/refs/merged_probe_file_combined_Charite_AG_DKMS_Panel_V5p1update_TE-93192476_hg38.bed"
  barcode_file: "/fast/users/altwassr_c/scratch/data/P1162/P1162_barcode1.csv"
  library_file: "/fast/users/altwassr_c/scratch/data/P1162/P1162_library_params1.csv"
  demux: TRUE

reference:  
  genome: "/fast/users/altwassr_c/work/refs/GRCh38.u2af1_fix.v1.2020_04_01.fa"
  known_indels: "/fast/users/altwassr_c/work/umi-data-processing/umi-preprocessing/refs/dbsnp.vcf.gz"

illumina:
  basecall_dir: "/fast/users/altwassr_c/scratch/data/P1162/Data/Intensities/BaseCalls/"
  readstructure: "148T8B9M8B148T"
  runbarcode: "2020"
  lane: "1"

picard:
  memoryusage: "-Xmx150g -Xms150g"

fgbio:
  groupreads: "-s adjacency"
  callconsensus: "-M 3"
  fextra: ""
  fminq: 5
