general:
  work_dir: "/data/gpfs-1/users/altwassr_c/scratch/P1519/demux"
  region_file: "/fast/users/altwassr_c/work/refs/merged_probe_file_DKMS_v5-hrd_1X_1p5X_hg38.bed"
  barcode_file_prefix: "/data/gpfs-1/users/altwassr_c/work/projekte/P1519/P1519_barcode"
  library_file_prefix: "/data/gpfs-1/users/altwassr_c/work/projekte/P1519/P1519_library_params"
  SampleSheet: "/data/gpfs-1/users/altwassr_c/scratch/data/P1519/SampleSheet_v2_template.csv"
  tmp_dir: "/data/gpfs-1/users/altwassr_c/scratch/tmp"
  demux: TRUE

reference:  
  genome: "/fast/users/altwassr_c/work/refs/GRCh38.u2af1_fix.v1.2020_04_01.fa"
  known_indels: "/fast/users/altwassr_c/work/umi-data-processing/umi-preprocessing/refs/dbsnp.vcf.gz"

illumina:
  basecall_dir: "/data/gpfs-1/users/altwassr_c/scratch/data/P1519/220609_A00643_0490_AH23CGDSX2/Data/Intensities/BaseCalls/"
  readstructure: "Y150,I8Y9,I8Y8,Y150"
  runbarcode: "2022"
  lane: ["1","2"]

picard:
  memoryusage: "-Xmx64g -Xms64g"

fgbio:
  groupreads: "-s adjacency"
  callconsensus: "-M 3"
  fextra: ""
  fminq: 5
  readstructure: "8B 8B 150T 9M 150T"
