general:
  work_dir: "/data/gpfs-1/users/altwassr_c/scratch/P1413/demux"
  region_file: "/fast/users/altwassr_c/work/refs/merged_probe_file_Charite_BeLove.bed"
  barcode_file_prefix: "/data/gpfs-1/users/altwassr_c/work/projekte/P1413/P1413_barcode"
  library_file_prefix: "/data/gpfs-1/users/altwassr_c/work/projekte/P1413/P1413_library_params"
  tmp_dir: "/data/gpfs-1/users/altwassr_c/scratch/tmp"
  demux: TRUE

reference:  
  genome: "/fast/users/altwassr_c/work/refs/GRCh38.u2af1_fix.v1.2020_04_01.fa"
  known_indels: "/fast/users/altwassr_c/work/umi-data-processing/umi-preprocessing/refs/dbsnp.vcf.gz"

illumina:
  basecall_dir: "/data/gpfs-1/users/altwassr_c/scratch/data/P1413/220325_A00643_0438_BH22YTDSX2/Data/Intensities/BaseCalls/"
  readstructure: "148T8B9M8B148T"
  runbarcode: "2020"
  lane: ["4"]

picard:
  memoryusage: "-Xmx64g -Xms64g"

fgbio:
  groupreads: "-s adjacency"
  callconsensus: "-M 5"
  fextra: ""
  fminq: 5
